### ISSUE TITLE
Install instructions are incorrect

### ISSUE THREAD

**Issue by mefellows** [austek/pact-avro-plugin#20]
This [line](https://github.com/austek/pact-avro-plugin/blob/main/docs/modules/ROOT/pages/getting_started.adoc?plain=1#L25) in the docs is incorrect:

```
✗ pact-plugin-cli -y install https://github.com/austek/pact-avro-plugin/releases/latest

2023-05-30T07:23:56.024139Z ERROR pact_plugin_cli: error - Downloading manifest file from GitHub
```

I think the release version needs to be pinned for that to work.

We should instead get it added to the registry so people can just go `pact-plugin-cli install -y avro`.

@uglyog how does one go about doing that? Or is that something we're reserving for "official" plugins?

**Comment by austek** [comment]
Actually, instructions are correct but the published artifacts are incorrect, the manifest file is, currently, packaged within the tar.gz file, where as `pact-plugin-cli` expects it to be outside

**Comment by mefellows** [comment]
hmm I'm still getting the following:

```
✗ ~/.pact/bin/pact-plugin-cli -y install https://github.com/austek/pact-avro-plugin/releases/latest
2023-05-30T23:37:42.975134Z ERROR pact_plugin_cli: error - Downloading manifest file from GitHub
Error: ExitCode(unix_exit_status(1))
➜  pact-go git:(example/avro) ✗ ~/.pact/bin/pact-plugin-cli -y install https://github.com/austek/pact-avro-plugin/releases/tag/v0.0.3

2023-05-30T23:37:50.242627Z ERROR pact_plugin_cli: error - Downloading manifest file from GitHub
Error: ExitCode(unix_exit_status(1))
```

**Comment by rholshausen** [comment]
`pact-plugin-cli` has commands for managing the registry files, and they get checked into GitHub.

**Comment by mefellows** [comment]
Ah, so they do. Should we add Avro there or is that reserved for "official" ones?

**Comment by rholshausen** [comment]
What are "official" ones?

I can add it, but I was envisioning a plugin author creating a PR with the updated index entries, which we can then merge. This is all undocumented.

**Comment by rholshausen** [comment]
Done, docs are here https://github.com/pact-foundation/pact-plugins/blob/main/docs/writing-plugin-guide.md#adding-plugins-to-the-pact-plugin-cli-index

**Comment by mefellows** [comment]
>What are "official" ones?

I don't know, was just trying to understand the process - thanks for the docs, I think that will be super helpful. I've updated the plugin workshop too.

**Comment by YOU54F** [comment]
oh that is nice Ron, will get that in our OSS update this month!
