### ISSUE TITLE
pact-avro-plugin fails to startup when pact-plugin-driver uses threads, rather than tokio tasks due to LogBack config

### ISSUE THREAD

**Issue by YOU54F** [austek/pact-avro-plugin#42]
See https://github.com/pact-foundation/pact-plugins/issues/68 for background.

When the pact-plugin-driver uses System threads for managing plugins, the Logback config in the pact-avro-plugin is causing issues.

This is rather than using tokio tasks (using threads was introduced for windows due to hanging plugin tests) and I would like to introduce for macos/linux (due to [segfaulting plugin tests](https://github.com/pact-foundation/pact-go/issues/269) in pact-go)

I have tried to narrow it down. 

The println for the servers port & serverKey is [here](https://github.com/pact-foundation/pact-go/issues/269)

The logback config is [here](https://github.com/austek/pact-avro-plugin/blob/main/modules/plugin/src/main/resources/logback.xml)

Removing these bits from the config ( the `RollingFileAppender` &  `AsyncAppender` ) allow the pact plugin statup message to be picked up

- https://github.com/austek/pact-avro-plugin/blob/6a7a8969202504e0880892465d2f8b77fdac3f68/modules/plugin/src/main/resources/logback.xml#L9-L29
- https://github.com/austek/pact-avro-plugin/blob/6a7a8969202504e0880892465d2f8b77fdac3f68/modules/plugin/src/main/resources/logback.xml#L33

Effectively this https://github.com/YOU54F/pact-avro-plugin/pull/2

I've tried removing just the `AsyncAppender` to no avail, so this means that to get the avro plugin to work on Windows, we need to disable the logging to file, and if we want to fix pact-go plugin behaviour on macos/linux, we will need to switch over to using threads, which means this issue will affect all users.

cc @uglyog - maybe you can shed some light on the world of java loggers

**Comment by YOU54F** [comment]
So I got the plugin started on windows and passing tests but it wont close cleanly as its invoked via a batch file. hmm

**Comment by rholshausen** [comment]
It may just need a flush after the println, as was done here: https://github.com/pact-foundation/pact-plugins/blob/main/plugins/protobuf/src/main/kotlin/io/pact/protobuf/plugin/PluginApp.kt#L57

**Comment by YOU54F** [comment]
Thanks Ron, Just tried that out and the same - only picks up the startup message if the file logger is removed

I noted that the plugin app there doesn't use file output

https://github.com/pact-foundation/pact-plugins/blob/main/plugins/protobuf/src/main/resources/logback.xml

FileAppender is documented here 

https://logback.qos.ch/manual/appenders.html#FileAppender

and there a few settings in there that may have an impact.
